INSERT INTO CUSTOMER (IDENTIFICATION, NAME, LASTNAME, IDENTIFICATION_TYPE)
VALUES ('1900875327', 'Bladimir', 'Minga', 'CEDULA');

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, AMOUNT, STATUS, TYPE, CUSTOMER_ID)
VALUES ('123-1', 100, 'ACTIVE', 'SAVINGS', 1);

INSERT INTO TRANSACTION (TRANSACTION_TYPE, AMOUNT, ACCOUNT_ID)
VALUES ('CREDIT', 10, 1);
